import { UptrailLogo } from "@/components/UptrailLogo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, Bot, CheckCircle2, Compass, Globe2, GraduationCap, LineChart, MapPin, MoveUpRight, Route, Sparkles, Target } from "lucide-react";
import { useLocation } from "wouter";

const capabilityCards = [
  { icon: Compass, title: "Career GPS", text: "Turn your current skills, experience, and destination into a route with a logical next step.", tone: "bg-[#E9F4EF] text-[#176653]" },
  { icon: LineChart, title: "Skill intelligence", text: "See readiness with evidence from self-reporting, assessments, and real projects.", tone: "bg-[#F1EDFF] text-[#6C55D7]" },
  { icon: Bot, title: "AI Career Mentor", text: "Ask better questions and get profile-aware explanations that make the next move feel clear.", tone: "bg-[#FFF2DF] text-[#A35B11]" },
];

export default function Home() {
  const [, setLocation] = useLocation();

  return (
    <main className="min-h-screen overflow-hidden bg-[#F8F7F2] text-[#1B2826]">
      <div className="mx-auto max-w-7xl px-5 sm:px-7 lg:px-10">
        <header className="flex h-20 items-center justify-between">
          <UptrailLogo />
          <nav className="hidden items-center gap-7 text-sm font-semibold text-[#62706A] md:flex"><a href="#how-it-works" className="transition-colors hover:text-[#18302F]">How it works</a><a href="#built-for-you" className="transition-colors hover:text-[#18302F]">For every stage</a><a href="#explore" className="transition-colors hover:text-[#18302F]">Explore careers</a></nav>
          <div className="flex items-center gap-2"><button onClick={() => startLogin()} className="hidden rounded-xl px-3 py-2 text-sm font-bold text-[#36514C] transition-colors hover:bg-white sm:block">Sign in</button><Button onClick={() => setLocation("/onboarding")} className="h-10 rounded-xl bg-[#18302F] px-4 font-bold text-white shadow-[0_10px_22px_rgba(24,48,47,0.15)] hover:bg-[#244442]">Find your path <ArrowRight className="ml-1.5 size-4" /></Button></div>
        </header>

        <section className="relative grid min-h-[580px] items-center gap-10 pb-14 pt-12 lg:grid-cols-[0.96fr_1.04fr] lg:py-20">
          <div className="relative z-10"><Badge className="border-0 bg-[#E5F2EA] px-3 py-1 text-xs font-bold tracking-wide text-[#176653] hover:bg-[#E5F2EA]"><Sparkles className="mr-1.5 size-3.5" />YOUR CAREER, MADE NAVIGABLE</Badge><h1 className="mt-6 max-w-xl font-display text-[3.25rem] font-semibold leading-[0.98] tracking-[-0.065em] text-[#18302F] sm:text-6xl lg:text-[4.8rem]">Take the next step with <span className="text-[#1F7863]">clarity.</span></h1><p className="mt-7 max-w-lg text-[1.05rem] leading-8 text-[#62706A]">Uptrail is your global career navigation system. Understand your position, choose a meaningful destination, and follow a route that adapts as you grow.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={() => setLocation("/onboarding")} size="lg" className="h-12 rounded-xl bg-[#18302F] px-6 text-[0.95rem] font-bold text-white shadow-[0_12px_26px_rgba(24,48,47,0.17)] hover:bg-[#244442]">Build your career map <ArrowRight className="ml-2 size-4" /></Button><Button onClick={() => setLocation("/explore")} variant="outline" size="lg" className="h-12 rounded-xl border-[#D8E1DA] bg-white px-6 text-[0.95rem] font-bold text-[#36514C] hover:bg-[#F1F6F2]">Explore career routes</Button></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-[#4F635D]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#1F7863]" />Global by design</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#1F7863]" />Your pace, your route</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#1F7863]" />Evidence-led progress</span></div></div>

          <div className="relative mx-auto w-full max-w-[600px] lg:mx-0"><div className="absolute -right-20 top-8 size-72 rounded-full bg-[#E4D7FF]/55 blur-3xl" /><div className="absolute -left-12 bottom-4 size-48 rounded-full bg-[#F7DCA1]/45 blur-3xl" /><div className="relative rounded-[2rem] border border-white/70 bg-white/90 p-4 shadow-[0_28px_80px_rgba(29,55,49,0.13)] backdrop-blur sm:p-5"><div className="flex items-center justify-between rounded-2xl bg-[#18302F] p-5 text-white"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#F4D793]">Your career GPS</p><p className="mt-2 font-display text-2xl font-semibold tracking-[-0.04em]">Frontend Developer</p></div><div className="grid size-11 place-items-center rounded-2xl bg-white/10"><Route className="size-5 text-[#F4D793]" /></div></div><div className="relative px-2 py-5 sm:px-4">{[["Today", "JavaScript · developing", "#6C55D7"], ["Next", "TypeScript foundations", "#1F7863"], ["Then", "Build with React", "#E08A34"], ["Proof", "2 portfolio projects", "#C75E76"], ["Destination", "Career-ready", "#18302F"]].map(([label, title, color], index) => <div key={title} className="relative flex gap-4 pb-4 last:pb-0"><div className="relative z-10 mt-1 grid size-8 shrink-0 place-items-center rounded-full border-[5px] border-white" style={{ backgroundColor: color }}>{index === 4 ? <Target className="size-3.5 text-white" /> : <span className="size-1.5 rounded-full bg-white" />}</div>{index < 4 && <div className="absolute left-4 top-8 h-[calc(100%-1rem)] border-l-2 border-dashed border-[#DCE5DF]" />}<div className="flex-1 rounded-xl bg-[#F8F9F7] px-4 py-3"><p className="text-[0.69rem] font-bold uppercase tracking-[0.15em] text-[#7A8B84]">{label}</p><p className="mt-1 text-sm font-bold text-[#263936]">{title}</p></div></div>)}</div><div className="rounded-2xl border border-[#DFE9E3] bg-[#F1F8F5] px-4 py-3"><p className="text-xs leading-5 text-[#397064]"><span className="font-bold text-[#1F6B5B]">Why this route?</span> It builds on your JavaScript foundation before introducing React.</p></div></div><div className="absolute -bottom-5 -left-5 hidden items-center gap-3 rounded-2xl border border-white bg-white p-3 shadow-[0_16px_32px_rgba(24,48,47,0.12)] sm:flex"><div className="grid size-9 place-items-center rounded-xl bg-[#FFF0D9] text-[#A35B11]"><Sparkles className="size-4" /></div><div><p className="text-xs font-bold text-[#1B2826]">High-impact next step</p><p className="mt-0.5 text-[0.7rem] text-[#6C7B75]">Learn TypeScript · 2 weeks</p></div></div></div>
        </section>
      </div>

      <section className="border-y border-[#E3E6DE] bg-white/60"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-[#E6E8E2] px-5 sm:grid-cols-4 sm:px-7 lg:px-10"><div className="py-6 sm:py-8"><p className="font-display text-3xl font-semibold tracking-[-0.04em] text-[#18302F]">5</p><p className="mt-1 text-xs font-semibold text-[#6D7A75]">career families to explore</p></div><div className="py-6 pl-5 sm:py-8 sm:pl-8"><p className="font-display text-3xl font-semibold tracking-[-0.04em] text-[#18302F]">3</p><p className="mt-1 text-xs font-semibold text-[#6D7A75]">ways to validate skills</p></div><div className="py-6 sm:py-8 sm:pl-8"><p className="font-display text-3xl font-semibold tracking-[-0.04em] text-[#18302F]">4</p><p className="mt-1 text-xs font-semibold text-[#6D7A75]">country profiles built in</p></div><div className="py-6 pl-5 sm:py-8 sm:pl-8"><p className="font-display text-3xl font-semibold tracking-[-0.04em] text-[#18302F]">1</p><p className="mt-1 text-xs font-semibold text-[#6D7A75]">route, continuously adaptable</p></div></div></section>

      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-7 lg:px-10 lg:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#1F7863]">MORE THAN A CAREER LIST</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-0.055em] text-[#18302F] sm:text-5xl">A thoughtful system for every career move.</h2><p className="mt-5 text-lg leading-8 text-[#66756E]">Uptrail works from your context to give you a clear direction, evidence-led priorities, and a practical rhythm of progress.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{capabilityCards.map((card) => <article key={card.title} className="group rounded-[1.7rem] border border-[#E2E6DF] bg-white p-7 shadow-[0_12px_26px_rgba(25,47,40,0.035)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[0_18px_34px_rgba(25,47,40,0.09)]"><div className={`grid size-12 place-items-center rounded-2xl ${card.tone}`}><card.icon className="size-5" /></div><h3 className="mt-8 font-display text-2xl font-semibold tracking-[-0.04em] text-[#1E302C]">{card.title}</h3><p className="mt-3 leading-7 text-[#687871]">{card.text}</p><button onClick={() => setLocation("/onboarding")} className="mt-7 inline-flex items-center gap-1.5 text-sm font-bold text-[#1F6B5B]">See how it works <MoveUpRight className="size-4" /></button></article>)}</div></section>

      <section id="built-for-you" className="bg-[#18302F] px-5 py-20 text-white sm:px-7 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><Badge className="border-0 bg-white/10 px-3 py-1 text-xs font-bold text-[#F4D793] hover:bg-white/10">BUILT FOR REAL TRANSITIONS</Badge><h2 className="mt-5 font-display text-4xl font-semibold leading-[1.03] tracking-[-0.055em] sm:text-5xl">Wherever you start, there is a next step.</h2><p className="mt-5 max-w-md leading-7 text-white/65">From school to the first role, from a career switch to a leadership move, your route respects the experience you already hold.</p><Button onClick={() => setLocation("/onboarding")} variant="outline" className="mt-8 h-11 rounded-xl border-white/25 bg-white/5 px-5 font-bold text-white hover:bg-white/10 hover:text-white">Tell us where you are <ArrowRight className="ml-2 size-4" /></Button></div><div className="grid gap-3 sm:grid-cols-2">{[[GraduationCap,"Students & graduates","Translate education into skills, projects, and first opportunities."],[Route,"Career switchers","Build on transferable strengths instead of starting from zero."],[Globe2,"Global professionals","Compare roles and pathways in a location-aware context."],[MapPin,"India-ready, globally useful","Education language and pathways flex by country without changing your career logic."]].map(([Icon, title, text]) => <div key={String(title)} className="rounded-2xl border border-white/10 bg-white/[0.045] p-5"><Icon className="size-5 text-[#F4D793]" /><h3 className="mt-5 text-sm font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-white/60">{String(text)}</p></div>)}</div></div></section>

      <section id="explore" className="mx-auto max-w-7xl px-5 py-20 text-center sm:px-7 lg:px-10"><div className="rounded-[2rem] bg-[#E7F1EA] px-6 py-14 sm:px-12"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#1F7863]">A MORE INTENTIONAL NEXT MOVE</p><h2 className="mx-auto mt-4 max-w-2xl font-display text-4xl font-semibold tracking-[-0.055em] text-[#18302F] sm:text-5xl">Your career is not a guess. It is a path you can see.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#5E7068]">Start with a lightweight profile and discover the route between today and your next professional destination.</p><Button onClick={() => setLocation("/onboarding")} className="mt-8 h-12 rounded-xl bg-[#18302F] px-6 font-bold text-white hover:bg-[#244442]">Create my career map <ArrowRight className="ml-2 size-4" /></Button></div></section>
    </main>
  );
}

