export const ENV = {
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerUserId: process.env.OWNER_USER_ID ? Number(process.env.OWNER_USER_ID) : undefined,
  isProduction: !process.argv.includes("--dev"),
  trustProxy: process.env.TRUST_PROXY === "true",
  aiBaseUrl: process.env.AI_BASE_URL ?? "https://api.openai.com/v1",
  aiApiKey: process.env.AI_API_KEY ?? "",
  aiChatModel: process.env.AI_CHAT_MODEL ?? "gpt-5-mini",
  aiImageModel: process.env.AI_IMAGE_MODEL ?? "gpt-image-1",
  aiTranscriptionModel: process.env.AI_TRANSCRIPTION_MODEL ?? "whisper-1",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "us-east-1",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3ForcePathStyle: process.env.S3_FORCE_PATH_STYLE === "true",
  notificationWebhookUrl: process.env.NOTIFICATION_WEBHOOK_URL ?? "",
};
